package dev.termish.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.compositionLocalOf
import androidx.compose.ui.text.intl.Locale

/**
 * 应用内文案（多语言）。
 *
 * Compose Multiplatform 的 composeResources 只能跟随系统语言，无法在应用内
 * 强制切换（资源环境 API 为 internal），因此这里用纯 Kotlin 层承载全部 UI
 * 文案：设置页选择 zh / en / 跟随系统 后，AppRoot 提供对应实例，全树通过
 * [LocalAppStrings] 读取。
 */
@Immutable
data class AppStrings(
    // 底栏
    val appTabHosts: String,
    val appTabConnections: String,
    val appTabSettings: String,
    // 主机列表
    val hostsAdd: String,
    val hostsSearch: String,
    val hostsEmpty: String,
    val hostsNoMatch: String,
    val hostsEdit: String,
    val hostsDelete: String,
    /** 批处理模式标题：已选数量（如 "2 selected"）。 */
    val hostsSelectedCount: (Int) -> String,
    val hostsSelectAll: String,
    val hostsConnect: String,
    val hostsDisconnect: String,
    val hostsRemove: String,
    /** 卡片会话下拉：关闭该主机的全部会话。 */
    val hostsCloseAll: String,
    /** 终端页添加菜单：通过 SFTP 连接（暂未实现）。 */
    val hostsConnectSftp: String,
    /** 首页连接失败 Snackbar 兜底文案。 */
    val hostsConnectFailed: String,
    /** SFTP 连接失败（带原因）。 */
    val sftpConnectFailed: (String) -> String,
    /** SFTP 断线 banner：连接已断开（红色，同终端错误样式）。 */
    val sftpDisconnected: String,
    /** SFTP 断线 banner：重新连接中（琥珀色，同终端重连样式）。 */
    val sftpReconnecting: String,
    val sftpReconnect: String,
    // SFTP
    val sftpNewTitle: String,
    val sftpUser: String,
    val sftpUpload: String,
    val sftpNewFolder: String,
    val sftpSortName: String,
    val sftpSortDate: String,
    val sftpSortSize: String,
    val sftpSortKind: String,
    val sftpChangeDownload: String,
    val sftpCopyPath: String,
    val sftpHiddenFiles: String,
    val sftpSearch: String,
    val sftpConnecting: String,
    val sftpFolderName: String,
    val sftpCreate: String,
    val sftpUploaded: String,
    val sftpCopied: String,
    val sftpDownload: String,
    val sftpDownloaded: String,
    val sftpDownloadFailed: (String) -> String,
    val sftpLoadFailed: (String) -> String,
    /** 卡片第二行：有活跃会话时显示（Termius 风格）。 */
    val hostsActive: String,
    /** 会话状态统计：已连接。 */
    val hostsConnected: String,
    val hostsModeSsh: String,
    val hostsModeMosh: String,
    // 主机编辑
    val editAddTitle: String,
    val editEditTitle: String,
    val editSave: String,
    val editName: String,
    val editHostname: String,
    val editPort: String,
    val editUsername: String,
    val editAuthMethod: String,
    val editAuthPassword: String,
    val editAuthKey: String,
    val editAuthKeyOrPassword: String,
    val editConnectionMode: String,
    val editModeSsh: String,
    val editModeMosh: String,
    val editPassword: String,
    val editPasswordKeep: String,
    val editPrivateKey: String,
    val editPrivateKeyKeep: String,
    val editTags: String,
    val editQuickCommands: String,
    val editStartupCommand: String,
    val editStartupPlaceholder: String,
    val editMoshThemeSync: String,
    val editMoshUdpPort: String,
    val editMoshUdpPortHint: String,
    // 连接页
    val connSearch: String,
    val connEmpty: String,
    val connNoMatch: String,
    val connDisconnect: String,
    val connRemove: String,
    val connStatusIdle: String,
    val connStatusConnecting: String,
    val connStatusAuth: String,
    val connStatusConnected: String,
    val connStatusClosed: String,
    val connStatusError: String,
    // 通用导航
    val navBack: String,
    val navMore: String,
    // 设置
    val settingsTitle: String,
    val settingsGroupAppearance: String,
    val settingsGroupTerminal: String,
    val settingsGroupGeneral: String,
    val settingsThemeDark: String,
    val settingsThemeLight: String,
    val settingsThemeSystem: String,
    val settingsAppTheme: String,
    val settingsTerminalPalette: String,
    /** 终端主题与字体二级页面。 */
    val settingsTerminalPageTitle: String,
    val settingsTerminalFontLabel: String,
    val settingsTerminalCols: String,
    val settingsTerminalType: String,
    val settingsManualFontSize: String,
    val settingsTerminalFontSize: String,
    val settingsHaptics: String,
    val settingsAutoReconnect: String,
    val settingsVerifyHostKey: String,
    val settingsOsc52Clipboard: String,
    val settingsClose: String,
    val settingsLanguage: String,
    val settingsLanguageSystem: String,
    val languageZh: String,
    val languageEn: String,
    // 分组标题（首页主机列表 / 连接页 / SFTP 选主机）
    val hostsSectionTitle: String,
    val connSectionTitle: String,
    val sftpSectionTitle: String,
    // 设置页「关于」区（版本/官网/联系/支持作者入口）
    val settingsGroupAbout: String,
    val settingsVersion: String,
    val settingsWebsite: String,
    val settingsContact: String,
    val settingsSupport: String,
    /** 微信收款码提示：微信无直链调起，只能保存图片后相册识别。 */
    val settingsSupportHint: String,
    /** 支持弹窗主按钮：直接唤起支付宝 App（qr.alipay.com universal link）。 */
    val settingsOpenAlipay: String,
    val settingsTabAlipay: String,
    val settingsTabWechat: String,
    // 终端页
    val terminalCancel: String,
    val terminalCopied: String,
    val terminalPasted: String,
    val terminalReconnectingN: (Int) -> String,
    /** mosh 链路失联提示：距上次收到对端包的秒数（会话保持中，恢复自动续传）。 */
    val terminalMoshLostContact: (Int) -> String,
    val terminalConnected: String,
    /** 链路失联（会话保持中）：状态点/会话列表在 mosh 失去联系时的文案。 */
    val terminalLinkLost: String,
    val terminalReconnecting: String,
    val terminalConnecting: String,
    val terminalAuthing: String,
    val terminalDisconnected: String,
    val terminalFailed: String,
    val terminalAuthRequired: String,
    val terminalConfirm: String,
    /** 关闭会话 tab 的确认弹窗。 */
    val terminalCloseTabTitle: String,
    val terminalCloseTabBody: (String) -> String,
    val terminalHostkeyChanged: String,
    val terminalHostkeyConfirm: String,
    val terminalHostkeyChangedBody: String,
    val terminalHostkeyBody: String,
    val terminalHostkeySaved: String,
    val terminalHostkeyCurrent: String,
    val terminalTrust: String,
)

/** 当前 UI 树使用的文案集合；由 AppRoot 根据设置注入。 */
val LocalAppStrings = compositionLocalOf<AppStrings> { EnStrings }

/** 根据设置解析语言：空 = 跟随系统（系统语言为中文时用中文，其余英文）。 */
fun appStringsFor(language: String): AppStrings = when (language) {
    "zh" -> ZhStrings
    "en" -> EnStrings
    else -> if (Locale.current.language.lowercase().startsWith("zh")) ZhStrings else EnStrings
}

private val EnStrings = AppStrings(
    appTabHosts = "Hosts",
    appTabConnections = "Connections",
    appTabSettings = "Settings",
    hostsAdd = "Add host",
    hostsSearch = "Search hosts / tags / users",
    hostsEmpty = "No hosts yet.\nTap + to add your first server.",
    hostsNoMatch = "No matching hosts",
    hostsEdit = "Edit",
    hostsDelete = "Delete",
    hostsSelectedCount = { "$it selected" },
    hostsSelectAll = "Select All",
    hostsConnect = "Connect",
    hostsDisconnect = "Disconnect",
    hostsRemove = "Remove",
    hostsCloseAll = "Close",
    hostsConnectSftp = "Connect via SFTP",
    hostsConnectFailed = "Connection failed",
    sftpConnectFailed = { "SFTP connection failed: $it" },
    sftpDisconnected = "Connection lost",
    sftpReconnecting = "Reconnecting…",
    sftpReconnect = "Reconnect",
    sftpNewTitle = "New SFTP connection",
    sftpUser = "User",
    sftpUpload = "Upload",
    sftpNewFolder = "New folder",
    sftpSortName = "Sort By name",
    sftpSortDate = "Sort by date",
    sftpSortSize = "Sort by size",
    sftpSortKind = "Sort By kind",
    sftpChangeDownload = "Change Download folder",
    sftpCopyPath = "Copy path",
    sftpHiddenFiles = "Hidden files",
    sftpSearch = "Search",
    sftpConnecting = "Connecting…",
    sftpFolderName = "Folder name",
    sftpCreate = "Create",
    sftpUploaded = "Uploaded",
    sftpCopied = "Path copied",
    sftpDownload = "Download to…",
    sftpDownloaded = "Downloaded",
    sftpDownloadFailed = { "Download failed: $it" },
    sftpLoadFailed = { "Failed to load: $it" },
    hostsActive = "Active",
    hostsConnected = "Connected",
    hostsModeSsh = "ssh",
    hostsModeMosh = "mosh",
    editAddTitle = "Add host",
    editEditTitle = "Edit host",
    editSave = "Save",
    editName = "Name",
    editHostname = "Host",
    editPort = "Port",
    editUsername = "Username",
    editAuthMethod = "Authentication",
    editAuthPassword = "Password",
    editAuthKey = "Private key",
    editAuthKeyOrPassword = "Key first, password fallback",
    editConnectionMode = "Connection",
    editModeSsh = "SSH",
    editModeMosh = "Mosh (requires mosh-server on the remote)",
    editPassword = "Password",
    editPasswordKeep = "Password (leave blank to keep)",
    editPrivateKey = "Private key (PEM)",
    editPrivateKeyKeep = "Private key (PEM, leave blank to keep)",
    editTags = "Tags (comma separated)",
    editQuickCommands = "Quick commands (one per line: label:command)",
    editStartupCommand = "Startup command (run after connect)",
    editStartupPlaceholder = "tmux new -A -s main (restore session on reconnect)",
    editMoshThemeSync = "Sync terminal theme to TUI (needs a startup command, e.g. herdr)",
    editMoshUdpPort = "Mosh UDP port (0 = auto)",
    editMoshUdpPortHint = "Fixed port for NAS/firewall port forwarding (e.g. 60001)",
    connSearch = "Search sessions / hosts / users",
    connEmpty = "No sessions\nOpen a host from the Hosts tab to connect",
    connNoMatch = "No matching sessions",
    connDisconnect = "Disconnect",
    connRemove = "Remove",
    connStatusIdle = "Not connected",
    connStatusConnecting = "Connecting",
    connStatusAuth = "Authenticating",
    connStatusConnected = "Connected",
    connStatusClosed = "Disconnected",
    connStatusError = "Connection failed",
    navBack = "Back",
    navMore = "More",
    settingsTitle = "Settings",
    settingsGroupAppearance = "Appearance",
    settingsGroupTerminal = "Terminal",
    settingsGroupGeneral = "General",
    settingsThemeDark = "Dark",
    settingsThemeLight = "Light",
    settingsThemeSystem = "Follow system",
    settingsAppTheme = "App theme",
    settingsTerminalPalette = "Terminal palette",
    settingsTerminalPageTitle = "Terminal theme & font",
    settingsTerminalFontLabel = "Font",
    settingsTerminalCols = "Terminal columns",
    settingsTerminalType = "Terminal type",
    settingsManualFontSize = "Manual font size",
    settingsTerminalFontSize = "Terminal font size",
    settingsHaptics = "Haptic feedback",
    settingsAutoReconnect = "Auto-reconnect",
    settingsVerifyHostKey = "Confirm host fingerprint on first connect",
    settingsOsc52Clipboard = "Allow remote clipboard (OSC 52)",
    settingsClose = "Close",
    settingsLanguage = "Language",
    settingsLanguageSystem = "Follow system",
    languageZh = "中文",
    languageEn = "English",
    hostsSectionTitle = "My hosts",
    connSectionTitle = "Sessions",
    sftpSectionTitle = "Select a host",
    settingsGroupAbout = "About",
    settingsVersion = "Version",
    settingsWebsite = "Website",
    settingsContact = "Contact",
    settingsSupport = "Support the developer",
    settingsSupportHint = "Long-press the QR code to save it, then open WeChat and scan from your album",
    settingsOpenAlipay = "Open Alipay",
    settingsTabAlipay = "Alipay",
    settingsTabWechat = "WeChat",
    terminalCancel = "Cancel",
    terminalCopied = "Copied",
    terminalPasted = "Pasted",
    terminalReconnectingN = { "Connection lost, reconnecting (attempt $it)…" },
    terminalMoshLostContact = { "No contact from server for $it s — session held, resumes on network recovery" },
    terminalConnected = "Connected",
    terminalLinkLost = "No contact",
    terminalReconnecting = "Reconnecting",
    terminalConnecting = "Connecting",
    terminalAuthing = "Authenticating",
    terminalDisconnected = "Disconnected",
    terminalFailed = "Connection failed",
    terminalAuthRequired = "Authentication required",
    terminalConfirm = "OK",
    terminalCloseTabTitle = "Close session?",
    terminalCloseTabBody = { host -> "Close the session to $host? This will disconnect the terminal." },
    terminalHostkeyChanged = "Server fingerprint changed",
    terminalHostkeyConfirm = "Confirm server identity",
    terminalHostkeyChangedBody =
        "The server fingerprint no longer matches the saved one (server reinstall, new machine, or port-forward changes).\n" +
            "Review the new fingerprint before deciding whether to trust it:",
    terminalHostkeyBody =
        "The authenticity of the server host cannot be verified. Check the fingerprint:",
    terminalHostkeySaved = "Saved:",
    terminalHostkeyCurrent = "Current",
    terminalTrust = "Trust and connect",
)

private val ZhStrings = AppStrings(
    appTabHosts = "主机",
    appTabConnections = "连接",
    appTabSettings = "设置",
    hostsAdd = "添加主机",
    hostsSearch = "搜索主机 / 标签 / 用户",
    hostsEmpty = "还没有主机。\n点击右下角 + 添加第一台服务器。",
    hostsNoMatch = "没有匹配的主机",
    hostsEdit = "编辑",
    hostsDelete = "删除",
    hostsSelectedCount = { "已选 $it 项" },
    hostsSelectAll = "全选",
    hostsConnect = "连接",
    hostsDisconnect = "断开",
    hostsRemove = "移除",
    hostsCloseAll = "关闭",
    hostsConnectSftp = "连接 SFTP",
    hostsConnectFailed = "连接失败",
    sftpConnectFailed = { "SFTP 连接失败：$it" },
    sftpDisconnected = "连接已断开",
    sftpReconnecting = "重新连接中…",
    sftpReconnect = "重新连接",
    sftpNewTitle = "新建 SFTP 连接",
    sftpUser = "User",
    sftpUpload = "上传",
    sftpNewFolder = "新建文件夹",
    sftpSortName = "按名称排序",
    sftpSortDate = "按日期排序",
    sftpSortSize = "按大小排序",
    sftpSortKind = "按类型排序",
    sftpChangeDownload = "更改下载文件夹",
    sftpCopyPath = "复制路径",
    sftpHiddenFiles = "显示隐藏文件",
    sftpSearch = "搜索",
    sftpConnecting = "连接中…",
    sftpFolderName = "文件夹名称",
    sftpCreate = "创建",
    sftpUploaded = "已上传",
    sftpCopied = "路径已复制",
    sftpDownload = "下载到…",
    sftpDownloaded = "已下载",
    sftpDownloadFailed = { "下载失败：$it" },
    sftpLoadFailed = { "加载失败：$it" },
    hostsActive = "Active",
    hostsConnected = "已连接",
    hostsModeSsh = "ssh",
    hostsModeMosh = "mosh",
    editAddTitle = "添加主机",
    editEditTitle = "编辑主机",
    editSave = "保存",
    editName = "名称",
    editHostname = "主机地址",
    editPort = "端口",
    editUsername = "用户名",
    editAuthMethod = "认证方式",
    editAuthPassword = "密码",
    editAuthKey = "私钥",
    editAuthKeyOrPassword = "私钥优先，密码兜底",
    editConnectionMode = "连接方式",
    editModeSsh = "SSH",
    editModeMosh = "Mosh（远端需安装 mosh-server）",
    editPassword = "密码",
    editPasswordKeep = "密码（留空保持不变）",
    editPrivateKey = "私钥 (PEM)",
    editPrivateKeyKeep = "私钥 (PEM，留空保持不变)",
    editTags = "标签（逗号分隔）",
    editQuickCommands = "快速命令（每行「标签:命令」）",
    editStartupCommand = "启动命令（连接后自动执行）",
    editStartupPlaceholder = "tmux new -A -s main（重连恢复现场）",
    editMoshThemeSync = "向 TUI 注入手机终端主题（需配置启动命令，如 herdr）",
    editMoshUdpPort = "Mosh UDP 端口（0 = 自动）",
    editMoshUdpPortHint = "NAS/防火墙端口转发时固定端口（如 60001）",
    connSearch = "搜索会话 / 主机 / 用户",
    connEmpty = "暂无会话\n在「主机」页点击主机即可发起连接",
    connNoMatch = "无匹配会话",
    connDisconnect = "断开",
    connRemove = "移除",
    connStatusIdle = "未连接",
    connStatusConnecting = "连接中",
    connStatusAuth = "认证中",
    connStatusConnected = "已连接",
    connStatusClosed = "已断开",
    connStatusError = "连接失败",
    navBack = "返回",
    navMore = "更多",
    settingsTitle = "设置",
    settingsGroupAppearance = "外观",
    settingsGroupTerminal = "终端",
    settingsGroupGeneral = "通用",
    settingsThemeDark = "深色",
    settingsThemeLight = "浅色",
    settingsThemeSystem = "跟随系统",
    settingsAppTheme = "应用主题",
    settingsTerminalPalette = "终端配色",
    settingsTerminalPageTitle = "终端主题与字体",
    settingsTerminalFontLabel = "字体",
    settingsTerminalCols = "终端列数",
    settingsTerminalType = "终端类型",
    settingsManualFontSize = "手动字号",
    settingsTerminalFontSize = "终端字号",
    settingsHaptics = "触感反馈",
    settingsAutoReconnect = "断线自动重连",
    settingsVerifyHostKey = "首次连接确认主机指纹",
    settingsOsc52Clipboard = "允许远端写剪贴板（OSC 52）",
    settingsClose = "关闭",
    settingsLanguage = "语言",
    settingsLanguageSystem = "跟随系统",
    languageZh = "中文",
    languageEn = "English",
    hostsSectionTitle = "我的主机",
    connSectionTitle = "会话",
    sftpSectionTitle = "选择主机",
    settingsGroupAbout = "关于",
    settingsVersion = "版本",
    settingsWebsite = "官网",
    settingsContact = "联系",
    settingsSupport = "支持作者",
    settingsSupportHint = "长按二维码保存图片，打开微信扫一扫从相册识别",
    settingsOpenAlipay = "打开支付宝",
    settingsTabAlipay = "支付宝",
    settingsTabWechat = "微信",
    terminalCancel = "取消",
    terminalCopied = "已复制",
    terminalPasted = "已粘贴",
    terminalReconnectingN = { "连接中断，正在重连（第 $it 次）…" },
    terminalMoshLostContact = { "与服务器失去联系 $it 秒——会话保持中，网络恢复后自动续传" },
    terminalConnected = "已连接",
    terminalLinkLost = "失联中",
    terminalReconnecting = "重连中",
    terminalConnecting = "连接中",
    terminalAuthing = "认证中",
    terminalDisconnected = "已断开",
    terminalFailed = "连接失败",
    terminalAuthRequired = "需要认证",
    terminalConfirm = "确定",
    terminalCloseTabTitle = "关闭会话？",
    terminalCloseTabBody = { host -> "关闭 $host 的会话？将断开该连接。" },
    terminalHostkeyChanged = "服务器指纹已变更",
    terminalHostkeyConfirm = "确认服务器身份",
    terminalHostkeyChangedBody =
        "该主机的服务器指纹与已保存的不一致（可能服务器重装、换机或端口转发变化）。\n" +
            "请核对新指纹后决定是否信任：",
    terminalHostkeyBody = "无法验证服务器主机的真实性。请核对指纹：",
    terminalHostkeySaved = "已保存：",
    terminalHostkeyCurrent = "当前",
    terminalTrust = "信任并连接",
)
