package dev.termish.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.compositionLocalOf
import androidx.compose.ui.text.intl.Locale

/**
 * 应用内文案（多语言）。
 *
 * Compose Multiplatform 的 composeResources 只能跟随系统语言，无法在应用内
 * 强制切换（资源环境 API 为 internal），因此这里用纯 Kotlin 层承载全部 UI
 * 文案：设置页选择 zh / en / 跟随系统 后，AppRoot 提供对应实例，全树通过
 * [LocalAppStrings] 读取。
 */
@Immutable
data class AppStrings(
    // 底栏
    val appTabHosts: String,
    val appTabConnections: String,
    val appTabSettings: String,
    // 主机列表
    val hostsAdd: String,
    val hostsSearch: String,
    val hostsEmpty: String,
    val hostsNoMatch: String,
    val hostsEdit: String,
    val hostsDelete: String,
    /** 批处理模式标题：已选数量（如 "2 selected"）。 */
    val hostsSelectedCount: (Int) -> String,
    val hostsSelectAll: String,
    val hostsConnect: String,
    val hostsDisconnect: String,
    val hostsRemove: String,
    /** 卡片会话下拉：关闭该主机的全部会话。 */
    val hostsCloseAll: String,
    /** 终端页添加菜单：通过 SFTP 连接（暂未实现）。 */
    val hostsConnectSftp: String,
    /** 首页连接失败 Snackbar 兜底文案。 */
    val hostsConnectFailed: String,
    /** SFTP 连接失败（带原因）。 */
    val sftpConnectFailed: (String) -> String,
    /** SFTP 断线 banner：连接已断开（红色，同终端错误样式）。 */
    val sftpDisconnected: String,
    /** SFTP 断线 banner：重新连接中（琥珀色，同终端重连样式）。 */
    val sftpReconnecting: String,
    val sftpReconnect: String,
    // SFTP
    val sftpNewTitle: String,
    val sftpUser: String,
    val sftpUpload: String,
    val sftpNewFolder: String,
    val sftpSortName: String,
    val sftpSortDate: String,
    val sftpSortSize: String,
    val sftpSortKind: String,
    val sftpChangeDownload: String,
    val sftpCopyPath: String,
    val sftpHiddenFiles: String,
    val sftpSearch: String,
    val sftpSearching: String,
    val sftpNoMatch: String,
    val sftpConnecting: String,
    val sftpFolderName: String,
    val sftpCreate: String,
    val sftpUploaded: String,
    val sftpCopied: String,
    val sftpDownload: String,
    val sftpDownloaded: String,
    val sftpDownloadComplete: String,
    val sftpDownloadFailed: (String) -> String,
    val sftpLoadFailed: (String) -> String,
    /** SFTP 文本预览（md/txt/log 等）。 */
    val sftpPreview: String,
    val sftpPreviewFailed: (String) -> String,
    /** 二进制文件无法预览。 */
    val sftpPreviewBinary: String,
    /** 预览截断提示（参数：显示的字节数，已格式化）。 */
    val sftpPreviewTruncated: (String) -> String,
    /** 预览内容已复制。 */
    val sftpPreviewCopied: String,
    /** 图片过大，无法预览。 */
    val sftpPreviewImageTooLarge: String,
    /** 图片预览：适配 / 原始大小切换。 */
    val sftpPreviewZoom: String,
    /** 卡片第二行：有活跃会话时显示（Termius 风格）。 */
    val hostsActive: String,
    /** 会话状态统计：已连接。 */
    val hostsConnected: String,
    val hostsModeSsh: String,
    val hostsModeMosh: String,
    val hostsModeHerdr: String,
    // 主机编辑
    val editAddTitle: String,
    val editEditTitle: String,
    val editSave: String,
    val editName: String,
    val editHostname: String,
    val editPort: String,
    val editUsername: String,
    val editAuthMethod: String,
    val editAuthPassword: String,
    val editAuthKey: String,
    val editAuthKeyOrPassword: String,
    val editConnectionMode: String,
    val editModeSsh: String,
    val editModeMosh: String,
    val editPassword: String,
    val editPasswordKeep: String,
    val editPrivateKey: String,
    val editPrivateKeyKeep: String,
    val editTags: String,
    val editStartupCommand: String,
    val editStartupPlaceholder: String,
    val editMoshThemeSync: String,
    val editLaunchHerdr: String,
    val agentPanelTitle: String,
    val agentUnknown: String,
    val agentPanelEmpty: String,
    val agentPanelUnavailable: String,
    val agentLoadingContext: String,
    val agentNoContext: String,
    val agentReplyHint: String,
    val agentReplySend: String,
    val agentReplyCancel: String,
    val agentPromptFailed: String,
    val agentReplySent: String,
    val editLaunchHerdrHint: String,
    val editAgentMonitoring: String,
    val editAgentMonitoringHint: String,
    val agentBlockedBadge: String,
    val agentWorkingBadge: String,
    val editMoshUdpPort: String,
    val editMoshUdpPortHint: String,
    // 连接页
    val connSearch: String,
    val connEmpty: String,
    val connNoMatch: String,
    val connDisconnect: String,
    val connRemove: String,
    val connStatusIdle: String,
    val connStatusConnecting: String,
    val connStatusAuth: String,
    val connStatusConnected: String,
    val connStatusClosed: String,
    val connStatusError: String,
    // 连接错误文案（SessionConnector 设置 errorMessage，终端 banner 展示）
    val moshPortBusy: (Int) -> String,
    val moshServerMissing: String,
    val moshBootstrapFailed: (String) -> String,
    val moshUdpDegraded: String,
    val herdrMissing: String,
    val herdrInstall: String,
    val herdrInstalling: String,
    val herdrInstallFailed: (String?) -> String,
    val herdrInstallHint: String,
    // mosh 引导安装（Mosh 模式远端未装 mosh-server：可安装或降级 SSH）
    val moshMissing: String,
    val moshInstall: String,
    val moshInstalling: String,
    val moshInstallFailed: (String?) -> String,
    /** 无法识别的系统：不能自动安装，提示手动安装（带已识别的系统标识）。 */
    val moshInstallUnsupported: (String) -> String,
    val moshInstallHint: String,
    /** 引导卡片上的降级按钮：放弃安装，用当前 SSH 连接继续。 */
    val moshDegradeToSsh: String,
    /** sudo 需要密码时：密码输入框 label。 */
    val moshSudoPasswordLabel: String,
    /** sudo 需要密码时：输入框提示文案。 */
    val moshSudoPasswordHint: String,
    val moshClientExited: String,
    val moshSessionError: String,
    val moshConnectTimeout: String,
    // 通用导航
    val navBack: String,
    val navMore: String,
    // 设置
    val settingsTitle: String,
    val settingsGroupTerminal: String,
    val settingsGroupGeneral: String,
    /** 通知设置入口（通用组）。 */
    val settingsNotifications: String,
    /** 设置页「命令片段」入口（通用组）：全局常用命令库。 */
    val settingsSnippets: String,
    /** 片段管理二级页标题。 */
    val snippetsTitle: String,
    /** 片段列表空态。 */
    val snippetsEmpty: String,
    val snippetsEmptyHint: String,
    val snippetsSearch: String,
    val snippetsAdd: String,
    /** 标签过滤 chips 的「全部」项。 */
    val snippetsTagAll: String,
    /** 片段表单字段。 */
    val snippetName: String,
    val snippetContent: String,
    val snippetTags: String,
    val snippetDeleteConfirm: String,
    /** 删除标签组的确认文案（n = 受影响的片段数）。 */
    val tagDeleteConfirm: (Int) -> String,
    /** 标签管理二级页。 */
    val tagsTitle: String,
    val tagsEmpty: String,
    val tagsHint: String,
    val tagName: String,
    val tagAdd: String,
    val tagDelete: String,
    /** 终端内插入面板。 */
    val snippetInsertTitle: String,
    val snippetInsertHint: String,
    val snippetRun: String,
    val snippetEdit: String,
    val snippetDelete: String,
    val snippetInserted: String,
    /** 主机编辑：结构化快速命令。 */
    /** 通知二级页。 */
    val settingsNotificationsTitle: String,
    val settingsNotificationsEnabled: String,
    val settingsNotificationsEvents: String,
    val settingsNotificationsSystem: String,
    /** 通用开/关值（通知行显示）。 */
    val settingsOn: String,
    val settingsOff: String,
    /** 诊断日志（设置页入口）。 */
    val settingsDiagnostics: String,
    val settingsDiagnosticsTitle: String,
    val settingsDiagnosticsEnabled: String,
    val settingsDiagnosticsExport: String,
    val settingsDiagnosticsPath: String,
    val settingsDiagnosticsHint: String,
    // 通知事件文案
    val notificationEventConnectionLost: String,
    val notificationEventReconnectFailed: String,
    val notificationEventTransferDone: String,
    val notificationEventAgentTask: String,
    /** 后台通知正文（SessionConnector 发通知；host = 主机名，reason = 引擎原因）。 */
    val notificationReconnectFailed: (String, String) -> String,
    val notificationConnectionLost: (String, String) -> String,
    /** 会话组（连接/保活/重连行为，Termius Session 分组）。 */
    val settingsGroupSession: String,
    val settingsThemeDark: String,
    val settingsThemeLight: String,
    val settingsThemeSystem: String,
    val settingsAppTheme: String,
    val settingsTerminalPalette: String,
    /** 终端主题与字体二级页面。 */
    val settingsTerminalPageTitle: String,
    val settingsTerminalFontLabel: String,
    val settingsTerminalCols: String,
    val settingsTerminalType: String,
    val settingsManualFontSize: String,
    val settingsTerminalFontSize: String,
    val settingsHaptics: String,
    val settingsAutoReconnect: String,
    /** 保活间隔（秒）：SSH 空闲保活，防 NAT/防火墙/服务器超时断连。 */
    val settingsKeepalive: String,
    /** 保活间隔 0 = 关闭。 */
    val settingsKeepaliveOff: String,
    val settingsVerifyHostKey: String,
    val settingsOsc52Clipboard: String,
    val settingsClose: String,
    val settingsLanguage: String,
    val settingsLanguageSystem: String,
    val languageZh: String,
    val languageEn: String,
    // 分组标题（首页主机列表 / 连接页 / SFTP 选主机）
    val hostsSectionTitle: String,
    val connSectionTitle: String,
    val sftpSectionTitle: String,
    // 设置页「关于」区（版本/官网/联系入口）
    val settingsGroupAbout: String,
    val settingsVersion: String,
    val settingsWebsite: String,
    val settingsContact: String,
    // 终端页
    val terminalCancel: String,
    val terminalCopied: String,
    val terminalPasted: String,
    val terminalReconnectingN: (Int) -> String,
    /** mosh 链路失联提示：距上次收到对端包的秒数（会话保持中，恢复自动续传）。 */
    val terminalMoshLostContact: (Int) -> String,
    val terminalConnected: String,
    /** 链路失联（会话保持中）：状态点/会话列表在 mosh 失去联系时的文案。 */
    val terminalLinkLost: String,
    val terminalReconnecting: String,
    val terminalConnecting: String,
    val terminalAuthing: String,
    val terminalDisconnected: String,
    val terminalFailed: String,
    val terminalAuthRequired: String,
    val terminalConfirm: String,
    /** 关闭会话 tab 的确认弹窗。 */
    val terminalCloseTabTitle: String,
    val terminalCloseTabBody: (String) -> String,
    val terminalHostkeyChanged: String,
    val terminalHostkeyConfirm: String,
    val terminalHostkeyChangedBody: String,
    val terminalHostkeyBody: String,
    val terminalHostkeySaved: String,
    val terminalHostkeyCurrent: String,
    val terminalTrust: String,
    /** 断开/失败 banner 的手动重连按钮。 */
    val terminalReconnect: String,
    // Git 面板（终端内可视化 git 状态/diff/提交）
    /** Git 面板文案（嵌套子类：主数据类构造参数受 JVM 255 上限约束）。 */
    val git: GitStrings,
    // 语音输入（火山引擎流式语音识别）
    val voice: VoiceStrings,
    // 终端文件上传
    val upload: UploadStrings,
    // 远程屏幕（视频推流）
    val screen: ScreenStrings,
    // SFTP 文件管理器扩展（多选/收藏/删除/分组等）
    val sftpExt: SftpExtStrings,
)

/** 语音输入文案（同 GitStrings：嵌套子类缓解 JVM 255 参数上限）。 */
@Immutable
data class VoiceStrings(
    /** 设置页入口（通用组）。 */
    val settingsVoice: String,
    /** 语音输入二级页标题。 */
    val settingsVoiceTitle: String,
    /** 总开关行。 */
    val settingsVoiceEnabled: String,
    /** 使用说明。 */
    val settingsVoiceHint: String,
    /** API Key 输入框 label。 */
    val settingsVoiceApiKey: String,
    /** API Key 获取位置提示。 */
    val settingsVoiceApiKeyHint: String,
    /** 控制台入口按钮。 */
    val settingsVoiceConsole: String,
    /** 资源 ID 输入框 label。 */
    val settingsVoiceResourceId: String,
    /** 资源 ID 提示。 */
    val settingsVoiceResourceHint: String,
    /** 未启用语音输入（设置页开关未开）。 */
    val disabled: String,
    /** 未配置 API Key。 */
    val notConfigured: String,
    /** 麦克风权限被拒。 */
    val noPermission: String,
    /** 误触提示（按住时间过短）。 */
    val holdToTalk: String,
    /** 录音中提示（波浪气泡内）。 */
    val listening: String,
    /** 识别中提示。 */
    val recognizing: String,
    /** 录音计时（秒）。 */
    val recordingSeconds: (Int) -> String,
    /** 功能菜单入口标签。 */
    val menuLabel: String,
    /** 长按语音按钮重置回中央的提示。 */
    val resetDone: String,
    /** 服务列表空态。 */
    val providerEmpty: String,
    /** 添加按钮。 */
    val providerAdd: String,
    /** 编辑按钮。 */
    val providerEdit: String,
    /** 服务名称字段。 */
    val providerName: String,
    /** 类型字段前缀（如「类型：火山引擎·流式识别」）。 */
    val providerTypeLabel: String,
    /** 火山引擎流式识别类型名。 */
    val providerTypeVolc: String,
    /** 未填密钥的标记。 */
    val providerNoKey: String,
    /** 删除确认标题（带名称）。 */
    val providerDeleteConfirmTitle: (String) -> String,
    /** 删除确认正文。 */
    val providerDeleteConfirmBody: String,
    /** 设置页入口显示启用服务数。 */
    val providerCount: (Int) -> String,
    /** 识别结果已发送（带文本）。 */
    val sent: (String) -> String,
    /** 识别失败（带原因）。 */
    val error: (String) -> String,
    /** 录音超时自动发送提示。 */
    val timeout: String,
)

/** 远程屏幕文案（H.264 推流播放，嵌套子类防 JVM 255 上限）。 */
@Immutable
data class ScreenStrings(
    /** 功能菜单入口标签（终端「+」菜单项）。 */
    val menuLabel: String,
    /** 连接中。 */
    val connecting: String,
    /** 重连按钮。 */
    val reconnect: String,
    /** 远端缺 ffmpeg 的引导提示。 */
    val ffmpegHint: String,
    /** 推流服务安装引导卡片标题。 */
    val serviceTitle: String,
    /** 推流服务安装引导卡片说明。 */
    val serviceHint: String,
    /** 安装服务按钮。 */
    val installService: String,
    /** 安装中。 */
    val installingService: String,
)

/** 终端文件上传文案（嵌套子类，同 GitStrings）。 */
@Immutable
data class UploadStrings(
    /** 功能菜单入口标签。 */
    val menuLabel: String,
    /** 文件管理菜单入口（打开 SFTP 文件管理视图）。 */
    val fileManagerLabel: String,
    /** 目标目录对话框标题。 */
    val dirTitle: String,
    /** 上传到当前目录。 */
    val dirCurrent: String,
    /** 上传到临时目录。 */
    val dirTmp: String,
    /** 探测当前目录失败时的提示。 */
    val dirNoWorkdir: String,
    /** 上传中（文件名 + 序号）。 */
    val uploading: (String) -> String,
    /** 进度百分比。 */
    val progress: (Int) -> String,
    /** 完成提示（N 个文件）。 */
    val done: (Int) -> String,
    /** 失败提示。 */
    val failed: (String) -> String,
)

/** SFTP 文件管理器扩展文案（多选 / 收藏 / 删除 / 分组，嵌套子类防 JVM 255 上限）。 */
@Immutable
data class SftpExtStrings(
    /** 时间分组：今天。 */
    val groupToday: String,
    /** 时间分组：本周。 */
    val groupWeek: String,
    /** 时间分组：更早。 */
    val groupEarlier: String,
    /** 空目录。 */
    val empty: String,
    /** 多选计数。 */
    val selected: (Int) -> String,
    /** 全选。 */
    val selectAll: String,
    /** 重命名。 */
    val rename: String,
    /** 删除。 */
    val delete: String,
    /** 删除确认标题（N 项）。 */
    val deleteConfirm: (Int) -> String,
    /** 删除确认正文。 */
    val deleteConfirmBody: String,
    /** 删除完成提示。 */
    val deleted: String,
    /** 重命名对话框标题。 */
    val renameTitle: String,
    /** 收藏当前目录（MoreMenu 项）。 */
    val favoriteAdd: String,
    /** 取消收藏当前目录（MoreMenu 项）。 */
    val favoriteRemove: String,
    /** 收藏夹（列表入口/对话框标题）。 */
    val favoritesTitle: String,
    /** 收藏列表空态。 */
    val favoritesEmpty: String,
    /** 刷新。 */
    val refresh: String,
)

/** Git 面板文案（终端内可视化 git 状态/diff/提交）。 */
@Immutable
data class GitStrings(
    val refresh: String,
    val close: String,
    val retry: String,
    val loading: String,
    val diffLoading: String,
    val empty: String,
    val noDiff: String,
    val noBranch: String,
    val changes: (Int) -> String,
    val stageAll: String,
    val unstageAll: String,
    val commit: String,
    val commitTitle: String,
    val commitMessage: String,
    val commitHint: String,
    val commitConfirm: String,
    val committed: String,
    val nothingToCommit: String,
    val notRepo: String,
    val notInstalled: String,
    val timeout: String,
    val fullscreenHint: String,
    val workdirUnknown: String,
    val stagedTab: String,
    val worktreeTab: String,
    val untracked: String,
    val conflicted: String,
    val diffTruncated: String,
    val dirHint: String,
    /** 功能菜单入口标签。 */
    val menuLabel: String,
)

/** 当前 UI 树使用的文案集合；由 AppRoot 根据设置注入。 */
val LocalAppStrings = compositionLocalOf<AppStrings> { EnStrings }

/** 根据设置解析语言：空 = 跟随系统（系统语言为中文时用中文，其余英文）。 */
fun appStringsFor(language: String): AppStrings = when (language) {
    "zh" -> ZhStrings
    "en" -> EnStrings
    else -> if (Locale.current.language.lowercase().startsWith("zh")) ZhStrings else EnStrings
}

private val EnStrings = AppStrings(
    appTabHosts = "Hosts",
    appTabConnections = "Connections",
    appTabSettings = "Settings",
    hostsAdd = "Add host",
    hostsSearch = "Search hosts / tags / users",
    hostsEmpty = "No hosts yet.\nTap + to add your first server.",
    hostsNoMatch = "No matching hosts",
    hostsEdit = "Edit",
    hostsDelete = "Delete",
    hostsSelectedCount = { "$it selected" },
    hostsSelectAll = "Select All",
    hostsConnect = "Connect",
    hostsDisconnect = "Disconnect",
    hostsRemove = "Remove",
    hostsCloseAll = "Close",
    hostsConnectSftp = "Connect via SFTP",
    hostsConnectFailed = "Connection failed",
    sftpConnectFailed = { "SFTP connection failed: $it" },
    sftpDisconnected = "Connection lost",
    sftpReconnecting = "Reconnecting…",
    sftpReconnect = "Reconnect",
    sftpNewTitle = "New SFTP connection",
    sftpUser = "User",
    sftpUpload = "Upload",
    sftpNewFolder = "New folder",
    sftpSortName = "Sort By name",
    sftpSortDate = "Sort by date",
    sftpSortSize = "Sort by size",
    sftpSortKind = "Sort By kind",
    sftpChangeDownload = "Change Download folder",
    sftpCopyPath = "Copy path",
    sftpHiddenFiles = "Hidden files",
    sftpSearch = "Search",
    sftpSearching = "Searching…",
    sftpNoMatch = "No matching files",
    sftpConnecting = "Connecting…",
    sftpFolderName = "Folder name",
    sftpCreate = "Create",
    sftpUploaded = "Uploaded",
    sftpCopied = "Path copied",
    sftpDownload = "Download to…",
    sftpDownloaded = "Downloaded",
    sftpDownloadComplete = "Download complete",
    sftpDownloadFailed = { "Download failed: $it" },
    sftpLoadFailed = { "Failed to load: $it" },
    sftpPreview = "Preview",
    sftpPreviewFailed = { "Preview failed: $it" },
    sftpPreviewBinary = "Cannot preview binary file",
    sftpPreviewTruncated = { "File too large — showing first $it" },
    sftpPreviewCopied = "Preview copied",
    sftpPreviewImageTooLarge = "Image too large to preview",
    sftpPreviewZoom = "Toggle fit / original size",
    hostsActive = "Active",
    hostsConnected = "Connected",
    hostsModeSsh = "ssh",
    hostsModeMosh = "mosh",
    hostsModeHerdr = "herdr",
    editAddTitle = "Add host",
    editEditTitle = "Edit host",
    editSave = "Save",
    editName = "Name",
    editHostname = "Host",
    editPort = "Port",
    editUsername = "Username",
    editAuthMethod = "Authentication",
    editAuthPassword = "Password",
    editAuthKey = "Private key",
    editAuthKeyOrPassword = "Key first, password fallback",
    editConnectionMode = "Connection",
    editModeSsh = "SSH",
    editModeMosh = "Mosh (requires mosh-server on the remote)",
    editPassword = "Password",
    editPasswordKeep = "Password (leave blank to keep)",
    editPrivateKey = "Private key (PEM)",
    editPrivateKeyKeep = "Private key (PEM, leave blank to keep)",
    editTags = "Tags (press Enter to add)",
    editStartupCommand = "Startup command (run after connect)",
    editStartupPlaceholder = "tmux new -A -s main (restore session on reconnect)",
    agentPanelTitle = "Agents",
    agentUnknown = "agent",
    agentPanelEmpty = "No agents running on connected hosts",
    agentPanelUnavailable = "Agent monitoring needs an active SSH session and herdr on the server",
    agentLoadingContext = "Loading context…",
    agentNoContext = "No recent output",
    agentReplyHint = "Reply to the agent…",
    agentReplySend = "Send",
    agentReplyCancel = "Cancel",
    agentPromptFailed = "Reply failed: %s",
    agentReplySent = "Reply sent",
    editLaunchHerdr = "Launch herdr workbench after connect",
    editLaunchHerdrHint = "Runs herdr (your coding agents' workspace) on connect; falls back to a plain shell if it exits",
    editAgentMonitoring = "Agent monitoring (herdr)",
    editAgentMonitoringHint = "Polls herdr api on the remote for status badges and notifications",
    agentBlockedBadge = "awaiting reply",
    agentWorkingBadge = "working",
    editMoshThemeSync = "Sync terminal theme to TUI (needs a startup command, e.g. herdr)",
    editMoshUdpPort = "Mosh UDP port (0 = auto)",
    editMoshUdpPortHint = "Fixed port for NAS/firewall port forwarding (e.g. 60001)",
    connSearch = "Search sessions / hosts / users",
    connEmpty = "No sessions\nOpen a host from the Hosts tab to connect",
    connNoMatch = "No matching sessions",
    connDisconnect = "Disconnect",
    connRemove = "Remove",
    connStatusIdle = "Not connected",
    connStatusConnecting = "Connecting",
    connStatusAuth = "Authenticating",
    connStatusConnected = "Connected",
    connStatusClosed = "Disconnected",
    connStatusError = "Connection failed",
    moshPortBusy = { "Fixed UDP port $it is in use" },
    moshServerMissing = "mosh-server not installed on remote (no bootstrap output)",
    moshBootstrapFailed = { "mosh-server bootstrap failed (no MOSH CONNECT; output: $it)" },
    moshUdpDegraded = "mosh UDP unreachable — degraded to SSH (for mosh roaming: check port forwarding/firewall; a fixed UDP port helps)",
    herdrMissing = "herdr is not installed on the remote server",
    herdrInstall = "Install",
    herdrInstalling = "Installing herdr…",
    herdrInstallFailed = { "herdr install failed: ${it ?: "unknown error"}" },
    herdrInstallHint = "herdr is the runtime your coding agents live on. Install it to attach to your agent workspace.",
    moshMissing = "mosh is not installed on the remote server",
    moshInstall = "Install mosh",
    moshInstalling = "Installing mosh…",
    moshInstallFailed = { "mosh install failed: ${it ?: "unknown error"}" },
    moshInstallUnsupported = { system -> "Cannot auto-install mosh (unknown system: $system). Install it manually, e.g. \"sudo apt install mosh\"." },
    moshInstallHint = "Installing mosh needs root (sudo) access on the remote. Once installed, Termish will reconnect over mosh automatically. You can also skip and keep using SSH.",
    moshDegradeToSsh = "Skip — use SSH",
    moshSudoPasswordLabel = "sudo password",
    moshSudoPasswordHint = "Installing mosh needs root. Enter your sudo password — it is sent over the encrypted SSH connection for this install only and never stored.",
    moshClientExited = "mosh connection failed: client exited",
    moshSessionError = "mosh session error",
    moshConnectTimeout = "mosh connection timed out — UDP unreachable (check port forwarding/firewall; a fixed UDP port helps)",
    navBack = "Back",
    navMore = "More",
    settingsTitle = "Settings",
    settingsGroupTerminal = "Terminal",
    settingsGroupGeneral = "General",
    settingsNotifications = "Notifications",
    settingsSnippets = "Snippets",
    snippetsTitle = "Snippets",
    snippetsEmpty = "No snippets yet",
    snippetsEmptyHint = "Tap + to save a reusable command",
    snippetsSearch = "Search snippets",
    snippetsAdd = "New snippet",
    snippetsTagAll = "All",
    snippetName = "Name",
    snippetContent = "Command",
    snippetTags = "Tags",
    snippetDeleteConfirm = "Delete this snippet?",
    tagDeleteConfirm = { n -> "Delete this tag? It will be removed from $n snippet${if (n == 1) "" else "s"}." },
    tagsTitle = "Manage tags",
    tagsEmpty = "No tags yet",
    tagsHint = "Tags group your snippets. Pick from these when creating a snippet — no free-text typing.",
    tagName = "Tag name",
    tagAdd = "Add",
    tagDelete = "Delete",
    snippetInsertTitle = "Insert snippet",
    snippetInsertHint = "Tap to insert at the cursor line",
    snippetRun = "Run now",
    snippetEdit = "Edit",
    snippetDelete = "Delete",
    snippetInserted = "Snippet inserted",
    settingsNotificationsTitle = "Notifications",
    settingsNotificationsEnabled = "Enable notifications",
    settingsNotificationsEvents = "Events",
    settingsNotificationsSystem = "System notification settings",
    settingsOn = "On",
    settingsOff = "Off",
    settingsDiagnostics = "Diagnostics",
    settingsDiagnosticsTitle = "Diagnostics",
    settingsDiagnosticsEnabled = "Diagnostic logs",
    settingsDiagnosticsExport = "Export logs",
    settingsDiagnosticsPath = "Log file",
    settingsDiagnosticsHint = "Temporarily enable detailed logging, reproduce the issue, then export and share the log file.",
    notificationEventConnectionLost = "Connection lost",
    notificationEventReconnectFailed = "Reconnect failed",
    notificationEventTransferDone = "Transfer finished",
    notificationEventAgentTask = "Agent task done",
    notificationReconnectFailed = { host, reason -> "$host: reconnect failed ($reason)" },
    notificationConnectionLost = { host, reason -> "$host: $reason" },
    settingsGroupSession = "Session",
    settingsThemeDark = "Dark",
    settingsThemeLight = "Light",
    settingsThemeSystem = "Follow system",
    settingsAppTheme = "App theme",
    settingsTerminalPalette = "Terminal palette",
    settingsTerminalPageTitle = "Terminal theme & font",
    settingsTerminalFontLabel = "Font",
    settingsTerminalCols = "Terminal columns",
    settingsTerminalType = "Terminal type",
    settingsManualFontSize = "Manual font size",
    settingsTerminalFontSize = "Terminal font size",
    settingsHaptics = "Haptic feedback",
    settingsAutoReconnect = "Auto-reconnect",
    settingsKeepalive = "Keep-alive interval",
    settingsKeepaliveOff = "Off",
    settingsVerifyHostKey = "Confirm host fingerprint on first connect",
    settingsOsc52Clipboard = "Allow remote clipboard (OSC 52)",
    settingsClose = "Close",
    settingsLanguage = "Language",
    settingsLanguageSystem = "Follow system",
    languageZh = "中文",
    languageEn = "English",
    hostsSectionTitle = "My hosts",
    connSectionTitle = "Sessions",
    sftpSectionTitle = "Select a host",
    settingsGroupAbout = "About",
    settingsVersion = "Version",
    settingsWebsite = "Website",
    settingsContact = "Contact",
    voice = VoiceStrings(
        settingsVoice = "Voice input",
        settingsVoiceTitle = "Voice input",
        settingsVoiceEnabled = "Enable voice input",
        settingsVoiceHint = "Hold the mic key in the terminal toolbar to speak; release to send the recognized text as terminal input. Powered by Volcano Engine streaming ASR (Doubao Voice).",
        settingsVoiceApiKey = "API Key",
        settingsVoiceApiKeyHint = "Get it from Volcano Engine console → Speech → API Key management.",
        settingsVoiceConsole = "Open Volcano Engine console",
        settingsVoiceResourceId = "Resource ID (model version)",
        settingsVoiceResourceHint = "The ASR service must be enabled for this key in the console; pick the plan you purchased.",
        disabled = "Voice input is off — enable it in Settings → Voice input",
        notConfigured = "Voice input is not configured — set your API Key in Settings → Voice input",
        noPermission = "Microphone permission is required for voice input",
        holdToTalk = "Spoke too briefly — tap the mic key and talk",
        listening = "Listening…",
        menuLabel = "Voice input",
        resetDone = "Voice button reset to center",
        providerEmpty = "No speech recognition service configured yet",
        providerAdd = "Add recognition service",
        providerEdit = "Edit",
        providerName = "Name",
        providerTypeLabel = "Type",
        providerTypeVolc = "Volcano Engine · Streaming ASR",
        providerNoKey = "no key",
        providerDeleteConfirmTitle = { n -> "Delete \"$n\"?" },
        providerDeleteConfirmBody = "The API Key of this service will be removed too.",
        providerCount = { n -> if (n == 1) "1 service" else "$n services" },
        recognizing = "Recognizing…",
        recordingSeconds = { "$it s" },
        sent = { "Sent: $it" },
        error = { "Voice recognition failed: $it" },
        timeout = "Speaking time limit reached — sending what was recognized",
    ),
    screen = ScreenStrings(
        menuLabel = "Remote screen",
        connecting = "Connecting to screen…",
        reconnect = "Reconnect",
        ffmpegHint = "Remote needs ffmpeg — install it on the Mac (e.g. `brew install ffmpeg` or download the static build), then reconnect.",
        serviceTitle = "Install screen streaming service",
        serviceHint = "macOS blocks screen capture from SSH sessions, so Termish runs a capture daemon on your Mac (GUI session). Tap install — takes about a minute, ffmpeg required.",
        installService = "Install service",
        installingService = "Installing…",
    ),
    upload = UploadStrings(
        menuLabel = "Upload file",
        fileManagerLabel = "File manager",
        dirTitle = "Upload to",
        dirCurrent = "Current directory",
        dirTmp = "Temp directory",
        dirNoWorkdir = "Current directory could not be detected",
        uploading = { n -> "Uploading $n" },
        progress = { p -> "$p%" },
        done = { n -> if (n == 1) "1 file uploaded" else "$n files uploaded" },
        failed = { msg -> "Upload failed: $msg" },
    ),
    sftpExt = SftpExtStrings(
        groupToday = "Today",
        groupWeek = "This week",
        groupEarlier = "Earlier",
        empty = "Empty folder",
        selected = { n -> "$n selected" },
        selectAll = "Select all",
        rename = "Rename",
        delete = "Delete",
        deleteConfirm = { n -> "Delete $n item(s)?" },
        deleteConfirmBody = "This permanently removes them and cannot be undone.",
        deleted = "Deleted",
        renameTitle = "Rename",
        favoriteAdd = "Favorite this folder",
        favoriteRemove = "Remove from favorites",
        favoritesTitle = "Favorites",
        favoritesEmpty = "No favorites yet",
        refresh = "Refresh",
    ),
    terminalCancel = "Cancel",
    terminalCopied = "Copied",
    terminalPasted = "Pasted",
    terminalReconnectingN = { "Connection lost, reconnecting (attempt $it)…" },
    terminalMoshLostContact = { "No contact from server for $it s — session held, resumes on network recovery" },
    terminalConnected = "Connected",
    terminalLinkLost = "No contact",
    terminalReconnecting = "Reconnecting",
    terminalConnecting = "Connecting",
    terminalAuthing = "Authenticating",
    terminalDisconnected = "Disconnected",
    terminalFailed = "Connection failed",
    terminalAuthRequired = "Authentication required",
    terminalConfirm = "OK",
    terminalCloseTabTitle = "Close session?",
    terminalCloseTabBody = { host -> "Close the session to $host? This will disconnect the terminal." },
    terminalHostkeyChanged = "Server fingerprint changed",
    terminalHostkeyConfirm = "Confirm server identity",
    terminalHostkeyChangedBody =
        "The server fingerprint no longer matches the saved one (server reinstall, new machine, or port-forward changes).\n" +
            "Review the new fingerprint before deciding whether to trust it:",
    terminalHostkeyBody =
        "The authenticity of the server host cannot be verified. Check the fingerprint:",
    terminalHostkeySaved = "Saved:",
    terminalHostkeyCurrent = "Current",
    terminalTrust = "Trust and connect",
    terminalReconnect = "Reconnect",
    git = GitStrings(
        refresh = "Refresh",
        close = "Close",
        retry = "Retry",
        loading = "Checking git status…",
        diffLoading = "Loading diff…",
        empty = "Working tree clean — no changes",
        noDiff = "No diff for this file",
        noBranch = "detached HEAD",
        changes = { n -> "$n changed" },
        stageAll = "Stage all",
        unstageAll = "Unstage",
        commit = "Commit",
        commitTitle = "Commit changes",
        commitMessage = "Commit message",
        commitHint = "Stages all changes and commits with this message.",
        commitConfirm = "Commit",
        committed = "Committed",
        nothingToCommit = "Nothing to commit — working tree clean",
        notRepo = "Not a git repository",
        notInstalled = "git not found on the remote",
        timeout = "git command timed out — check the connection",
        fullscreenHint = "Exit full-screen programs (vim/tmux) first to use the Git panel",
        workdirUnknown = "Unable to determine the remote working directory",
        stagedTab = "Staged",
        worktreeTab = "Worktree",
        untracked = "Untracked",
        conflicted = "Conflict",
        diffTruncated = "Diff too large — showing the first 600 lines",
        dirHint = "Untracked folder — open it in the terminal to explore",
        menuLabel = "Git",
    ),
)

private val ZhStrings = AppStrings(
    appTabHosts = "主机",
    appTabConnections = "连接",
    appTabSettings = "设置",
    hostsAdd = "添加主机",
    hostsSearch = "搜索主机 / 标签 / 用户",
    hostsEmpty = "还没有主机。\n点击右下角 + 添加第一台服务器。",
    hostsNoMatch = "没有匹配的主机",
    hostsEdit = "编辑",
    hostsDelete = "删除",
    hostsSelectedCount = { "已选 $it 项" },
    hostsSelectAll = "全选",
    hostsConnect = "连接",
    hostsDisconnect = "断开",
    hostsRemove = "移除",
    hostsCloseAll = "关闭",
    hostsConnectSftp = "连接 SFTP",
    hostsConnectFailed = "连接失败",
    sftpConnectFailed = { "SFTP 连接失败：$it" },
    sftpDisconnected = "连接已断开",
    sftpReconnecting = "重新连接中…",
    sftpReconnect = "重新连接",
    sftpNewTitle = "新建 SFTP 连接",
    sftpUser = "User",
    sftpUpload = "上传",
    sftpNewFolder = "新建文件夹",
    sftpSortName = "按名称排序",
    sftpSortDate = "按日期排序",
    sftpSortSize = "按大小排序",
    sftpSortKind = "按类型排序",
    sftpChangeDownload = "更改下载文件夹",
    sftpCopyPath = "复制路径",
    sftpHiddenFiles = "显示隐藏文件",
    sftpSearch = "搜索",
    sftpSearching = "搜索中…",
    sftpNoMatch = "没有匹配的文件",
    sftpConnecting = "连接中…",
    sftpFolderName = "文件夹名称",
    sftpCreate = "创建",
    sftpUploaded = "已上传",
    sftpCopied = "路径已复制",
    sftpDownload = "下载到…",
    sftpDownloaded = "已下载",
    sftpDownloadComplete = "下载完成",
    sftpDownloadFailed = { "下载失败：$it" },
    sftpLoadFailed = { "加载失败：$it" },
    sftpPreview = "预览",
    sftpPreviewFailed = { "预览失败：$it" },
    sftpPreviewBinary = "二进制文件无法预览",
    sftpPreviewTruncated = { "文件过大，仅显示前 $it" },
    sftpPreviewCopied = "预览内容已复制",
    sftpPreviewImageTooLarge = "图片过大，无法预览",
    sftpPreviewZoom = "切换适配 / 原始大小",
    hostsActive = "Active",
    hostsConnected = "已连接",
    hostsModeSsh = "ssh",
    hostsModeMosh = "mosh",
    hostsModeHerdr = "herdr",
    editAddTitle = "添加主机",
    editEditTitle = "编辑主机",
    editSave = "保存",
    editName = "名称",
    editHostname = "主机地址",
    editPort = "端口",
    editUsername = "用户名",
    editAuthMethod = "认证方式",
    editAuthPassword = "密码",
    editAuthKey = "私钥",
    editAuthKeyOrPassword = "私钥优先，密码兜底",
    editConnectionMode = "连接方式",
    editModeSsh = "SSH",
    editModeMosh = "Mosh（远端需安装 mosh-server）",
    editPassword = "密码",
    editPasswordKeep = "密码（留空保持不变）",
    editPrivateKey = "私钥 (PEM)",
    editPrivateKeyKeep = "私钥 (PEM，留空保持不变)",
    editTags = "标签（回车/逗号添加）",
    editStartupCommand = "启动命令（连接后自动执行）",
    editStartupPlaceholder = "tmux new -A -s main（重连恢复现场）",
    agentPanelTitle = "Agents",
    agentUnknown = "agent",
    agentPanelEmpty = "No agents running on connected hosts",
    agentPanelUnavailable = "Agent monitoring needs an active SSH session and herdr on the server",
    agentLoadingContext = "Loading context…",
    agentNoContext = "No recent output",
    agentReplyHint = "Reply to the agent…",
    agentReplySend = "Send",
    agentReplyCancel = "Cancel",
    agentPromptFailed = "Reply failed: %s",
    agentReplySent = "Reply sent",
    editLaunchHerdr = "连接后启动 herdr 工作台",
    editLaunchHerdrHint = "连接后自动运行 herdr（agent 工作台）；退出 herdr 后回到普通 shell",
    editAgentMonitoring = "Agent 监控（herdr）",
    editAgentMonitoringHint = "在远端执行 herdr api 轮询，驱动状态徽章/通知",
    agentBlockedBadge = "等待回复",
    agentWorkingBadge = "运行中",
    editMoshThemeSync = "向 TUI 注入手机终端主题（需配置启动命令，如 herdr）",
    editMoshUdpPort = "Mosh UDP 端口（0 = 自动）",
    editMoshUdpPortHint = "NAS/防火墙端口转发时固定端口（如 60001）",
    connSearch = "搜索会话 / 主机 / 用户",
    connEmpty = "暂无会话\n在「主机」页点击主机即可发起连接",
    connNoMatch = "无匹配会话",
    connDisconnect = "断开",
    connRemove = "移除",
    connStatusIdle = "未连接",
    connStatusConnecting = "连接中",
    connStatusAuth = "认证中",
    connStatusConnected = "已连接",
    connStatusClosed = "已断开",
    connStatusError = "连接失败",
    moshPortBusy = { "固定 UDP 端口 $it 被占用" },
    moshServerMissing = "远端未安装 mosh-server（引导无输出）",
    moshBootstrapFailed = { "mosh-server 引导失败（无 MOSH CONNECT；输出：$it）" },
    moshUdpDegraded = "mosh UDP 不可达，已降级到 SSH 连接（如需 mosh 漫游：检查端口转发/防火墙，固定 UDP 端口可解）",
    herdrMissing = "远端服务器未安装 herdr",
    herdrInstall = "安装",
    herdrInstalling = "正在安装 herdr…",
    herdrInstallFailed = { "herdr 安装失败：${it ?: "未知错误"}" },
    herdrInstallHint = "herdr 是 coding agent 的运行环境，安装后即可从手机接入你的 agent 工作台",
    moshMissing = "远端服务器未安装 mosh",
    moshInstall = "安装 mosh",
    moshInstalling = "正在安装 mosh…",
    moshInstallFailed = { "mosh 安装失败：${it ?: "未知错误"}" },
    moshInstallUnsupported = { system -> "无法自动安装 mosh（无法识别的系统：$system）。请手动安装，例如 \"sudo apt install mosh\"。" },
    moshInstallHint = "安装 mosh 需要远端 root（sudo）权限。安装完成后将自动重连 mosh；也可以跳过，继续使用 SSH 连接。",
    moshDegradeToSsh = "跳过，改用 SSH",
    moshSudoPasswordLabel = "sudo 密码",
    moshSudoPasswordHint = "安装 mosh 需要 root 权限。请输入 sudo 密码——仅通过加密 SSH 连接用于本次安装，不会保存。",
    moshClientExited = "mosh 连接失败：客户端已退出",
    moshSessionError = "mosh 会话异常",
    moshConnectTimeout = "mosh 连接超时：UDP 端口不可达（检查端口转发/防火墙，固定 UDP 端口可解）",
    navBack = "返回",
    navMore = "更多",
    settingsTitle = "设置",
    settingsGroupTerminal = "终端",
    settingsGroupGeneral = "通用",
    settingsNotifications = "通知",
    settingsSnippets = "命令片段",
    snippetsTitle = "命令片段",
    snippetsEmpty = "还没有命令片段",
    snippetsEmptyHint = "点右下角 + 保存常用命令，终端里一键插入",
    snippetsSearch = "搜索片段",
    snippetsAdd = "新建片段",
    snippetsTagAll = "全部",
    snippetName = "名称",
    snippetContent = "命令内容",
    snippetTags = "标签",
    snippetDeleteConfirm = "删除该片段？",
    tagDeleteConfirm = { n -> "删除该标签？将从 $n 个片段中移除。" },
    tagsTitle = "标签管理",
    tagsEmpty = "还没有标签",
    tagsHint = "标签用于归类片段：创建片段时从标签组中选择，无需手输。",
    tagName = "标签名",
    tagAdd = "添加",
    tagDelete = "删除",
    snippetInsertTitle = "插入片段",
    snippetInsertHint = "点按插入到当前输入行（不带回车）",
    snippetRun = "直接执行",
    snippetEdit = "编辑",
    snippetDelete = "删除",
    snippetInserted = "已插入片段",
    settingsNotificationsTitle = "通知",
    settingsNotificationsEnabled = "开启通知",
    settingsNotificationsEvents = "通知事件",
    settingsNotificationsSystem = "系统通知设置",
    settingsOn = "开",
    settingsOff = "关",
    settingsDiagnostics = "诊断",
    settingsDiagnosticsTitle = "诊断",
    settingsDiagnosticsEnabled = "诊断日志",
    settingsDiagnosticsExport = "导出日志",
    settingsDiagnosticsPath = "日志文件",
    settingsDiagnosticsHint = "临时开启详细日志，复现问题后导出并分享日志文件。排查完请关闭。",
    notificationEventConnectionLost = "连接断开",
    notificationEventReconnectFailed = "重连失败",
    notificationEventTransferDone = "传输完成",
    notificationEventAgentTask = "Agent 任务完成",
    notificationReconnectFailed = { host, reason -> "$host：重连失败（$reason）" },
    notificationConnectionLost = { host, reason -> "$host：$reason" },
    settingsGroupSession = "会话",
    settingsThemeDark = "深色",
    settingsThemeLight = "浅色",
    settingsThemeSystem = "跟随系统",
    settingsAppTheme = "应用主题",
    settingsTerminalPalette = "终端配色",
    settingsTerminalPageTitle = "终端主题与字体",
    settingsTerminalFontLabel = "字体",
    settingsTerminalCols = "终端列数",
    settingsTerminalType = "终端类型",
    settingsManualFontSize = "手动字号",
    settingsTerminalFontSize = "终端字号",
    settingsHaptics = "触感反馈",
    settingsAutoReconnect = "断线自动重连",
    settingsKeepalive = "保活间隔",
    settingsKeepaliveOff = "关闭",
    settingsVerifyHostKey = "首次连接确认主机指纹",
    settingsOsc52Clipboard = "允许远端写剪贴板（OSC 52）",
    settingsClose = "关闭",
    settingsLanguage = "语言",
    settingsLanguageSystem = "跟随系统",
    languageZh = "中文",
    languageEn = "English",
    hostsSectionTitle = "我的主机",
    connSectionTitle = "会话",
    sftpSectionTitle = "选择主机",
    settingsGroupAbout = "关于",
    settingsVersion = "版本",
    settingsWebsite = "官网",
    settingsContact = "联系",
    voice = VoiceStrings(
        settingsVoice = "语音输入",
        settingsVoiceTitle = "语音输入",
        settingsVoiceEnabled = "启用语音输入",
        settingsVoiceHint = "按住终端工具栏的麦克风键说话，松手自动把识别出的文字发送到终端。由火山引擎流式语音识别（豆包语音）提供能力。",
        settingsVoiceApiKey = "API Key",
        settingsVoiceApiKeyHint = "在火山引擎控制台「语音技术 → API Key 管理」中获取。",
        settingsVoiceConsole = "打开火山引擎控制台",
        settingsVoiceResourceId = "资源 ID（模型版本）",
        settingsVoiceResourceHint = "需先在控制台为当前 Key 开通对应的流式语音识别服务，按购买的套餐选择。",
        disabled = "语音输入未开启：请在设置 → 语音输入中打开开关",
        notConfigured = "语音输入未配置：请在设置 → 语音输入中填写 API Key",
        noPermission = "语音输入需要麦克风权限",
        holdToTalk = "录音时间太短，请点开麦克风再说话",
        listening = "正在聆听…",
        menuLabel = "语音输入",
        resetDone = "语音按钮已重置到屏幕中央",
        providerEmpty = "还没有配置语音识别服务",
        providerAdd = "添加识别服务",
        providerEdit = "编辑",
        providerName = "名称",
        providerTypeLabel = "类型",
        providerTypeVolc = "火山引擎 · 流式识别",
        providerNoKey = "未填密钥",
        providerDeleteConfirmTitle = { n -> "删除「$n」？" },
        providerDeleteConfirmBody = "该服务的 API Key 也会一并清除。",
        providerCount = { n -> "$n 个服务" },
        recognizing = "识别中…",
        recordingSeconds = { "$it 秒" },
        sent = { "已发送：$it" },
        error = { "语音识别失败：$it" },
        timeout = "说话时间到，已发送识别到的内容",
    ),
    screen = ScreenStrings(
        menuLabel = "远程画面",
        connecting = "正在连接画面…",
        reconnect = "重新连接",
        ffmpegHint = "远端需要 ffmpeg——在 Mac 上安装（如 `brew install ffmpeg` 或下载静态版）后重新连接。",
        serviceTitle = "安装屏幕推流服务",
        serviceHint = "macOS 禁止 SSH 会话直接录屏，Termish 会在你的 Mac 上安装一个常驻推流服务（跑在登录会话里）。点安装即可，约 1 分钟（需已装 ffmpeg）。",
        installService = "安装服务",
        installingService = "正在安装…",
    ),
    upload = UploadStrings(
        menuLabel = "上传文件",
        fileManagerLabel = "文件管理",
        dirTitle = "上传到",
        dirCurrent = "当前目录",
        dirTmp = "临时目录",
        dirNoWorkdir = "无法探测当前目录",
        uploading = { n -> "上传中 $n" },
        progress = { p -> "$p%" },
        done = { n -> "已上传 $n 个文件" },
        failed = { msg -> "上传失败：$msg" },
    ),
    sftpExt = SftpExtStrings(
        groupToday = "今天",
        groupWeek = "本周",
        groupEarlier = "更早",
        empty = "空目录",
        selected = { n -> "已选 $n 项" },
        selectAll = "全选",
        rename = "重命名",
        delete = "删除",
        deleteConfirm = { n -> "删除 $n 项？" },
        deleteConfirmBody = "将永久删除，且不可恢复。",
        deleted = "已删除",
        renameTitle = "重命名",
        favoriteAdd = "收藏当前目录",
        favoriteRemove = "取消收藏当前目录",
        favoritesTitle = "收藏夹",
        favoritesEmpty = "还没有收藏",
        refresh = "刷新",
    ),
    terminalCancel = "取消",
    terminalCopied = "已复制",
    terminalPasted = "已粘贴",
    terminalReconnectingN = { "连接中断，正在重连（第 $it 次）…" },
    terminalMoshLostContact = { "与服务器失去联系 $it 秒——会话保持中，网络恢复后自动续传" },
    terminalConnected = "已连接",
    terminalLinkLost = "失联中",
    terminalReconnecting = "重连中",
    terminalConnecting = "连接中",
    terminalAuthing = "认证中",
    terminalDisconnected = "已断开",
    terminalFailed = "连接失败",
    terminalAuthRequired = "需要认证",
    terminalConfirm = "确定",
    terminalCloseTabTitle = "关闭会话？",
    terminalCloseTabBody = { host -> "关闭 $host 的会话？将断开该连接。" },
    terminalHostkeyChanged = "服务器指纹已变更",
    terminalHostkeyConfirm = "确认服务器身份",
    terminalHostkeyChangedBody =
        "该主机的服务器指纹与已保存的不一致（可能服务器重装、换机或端口转发变化）。\n" +
            "请核对新指纹后决定是否信任：",
    terminalHostkeyBody = "无法验证服务器主机的真实性。请核对指纹：",
    terminalHostkeySaved = "已保存：",
    terminalHostkeyCurrent = "当前",
    terminalTrust = "信任并连接",
    terminalReconnect = "重新连接",
    git = GitStrings(
        refresh = "刷新",
        close = "关闭",
        retry = "重试",
        loading = "正在查询 git 状态…",
        diffLoading = "正在加载 diff…",
        empty = "工作区干净，没有改动",
        noDiff = "该文件没有差异",
        noBranch = "游离 HEAD（无分支）",
        changes = { n -> "改动 $n 个文件" },
        stageAll = "全部暂存",
        unstageAll = "取消暂存",
        commit = "提交",
        commitTitle = "提交改动",
        commitMessage = "提交说明",
        commitHint = "将暂存全部改动并按此说明提交。",
        commitConfirm = "提交",
        committed = "已提交",
        nothingToCommit = "没有可提交的改动——工作区干净",
        notRepo = "不是 git 仓库",
        notInstalled = "远端未安装 git",
        timeout = "git 命令超时——请检查连接",
        fullscreenHint = "请先退出全屏程序（vim/tmux）再使用 Git 面板",
        workdirUnknown = "无法确定远端工作目录",
        stagedTab = "已暂存",
        worktreeTab = "未暂存",
        untracked = "未跟踪",
        conflicted = "冲突",
        diffTruncated = "差异过大——仅显示前 600 行",
        dirHint = "未跟踪目录——请在终端中查看",
        menuLabel = "Git",
    ),
)
